
import React from 'react';
import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import Layout from '@/components/Layout';
import AnimatedText from '@/components/AnimatedText';
import HireMe from '@/components/HireMe';
import { LinkArrow } from '@/components/Icons';
import dev0 from "../../public/images/profile/dev0.png";

export default function Home() {
  return (
    <>
      <Head>
        <title>Kevin's Portfolio | Home</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main className='flex items-center bg-light dark:bg-dark dark:border-dark dark:text-light w-full min-h-screen'>
        <Layout className='mx-5'>

          <div className="flex items-center justify-center w-full h-60 mx-30">
            <div className='w-1/2 flex flex-col items-center self-center mx-20'>
              <AnimatedText 
              text="Welcome to my portfolio!" 
              className='!text-6xl !text-left'/>
              
              <p className='my-4 text-xl font-medium pr-5'>
                My name is Kevin Gao and I am a passionate university graduate who is eager to contribute to a software engineering environment. 
                <br></br>
                <br></br>
                Feel free to explore my portfolio and check out my resume. 
                <br></br>
                <br></br>
                If you're curious of the pictures on the portfolio were made using a Stable Diffusion Image Generation Model!
              </p>
              
              <div className='flex items-center self-start mt-2'>
                <Link 
                  href="/GeneralResume.pdf" 
                  target={"_blank"} 
                  className="flex items-center bg-dark text-light dark:bg-light dark:text-dark p-2.5 px-6 rounded-lg text-lg font-semibold hover:bg-light hover:text-dark dark:hover:bg-dark dark:hover:text-light border-2 border-solid border-transpartent hover:border-dark dark:hover:border-light"
                  download={true}>
                  Resume
                  <LinkArrow className={"w-6 ml-1"}/>
                </Link>
                
              </div>
            </div>

            <div className='w=full items-center'>
              <Image 
              src={dev0} 
              alt="main portfolio picture" 
              className='w-full h-auto rounded-full' />
            </div>
          </div>

          <HireMe/>

        </Layout>
      </main>
    </>
  )
}
